### PR TITLE
LPS-130276, LPS-130277,LPS-130278,LPS-130279 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130276
https://issues.liferay.com/browse/LPS-130277
https://issues.liferay.com/browse/LPS-130278
https://issues.liferay.com/browse/LPS-130279

Hi @CarlosBrichete , could you review these cases when you have time?

Thanks!

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @liulukiwi , this test SegmentationCreateSegment#AddSegmentByOrganizationDateModified is failing, not sure if this test was implemented in this PR though.

**Comment by liulukiwi** [comment]
Thanks @CarlosBrichete , That's my fault, I will fix it.

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Thank you very much @liulukiwi !!!👍  🥇

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
