### PR TITLE
LPS-120617 Poshi Automation: Validate if the user is able to edit a Web Content in the Content Dashboard through the Edit option

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
