### PR TITLE
LPS-130346,LPS-130347,LPS-130348,LPS-132107,LPS-132108 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130346
https://issues.liferay.com/browse/LPS-130347
https://issues.liferay.com/browse/LPS-130348
https://issues.liferay.com/browse/LPS-132108
https://issues.liferay.com/browse/LPS-132107

Hi @CarlosBrichete , could you review these cases when you have time?

Thanks!

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete , would you like to run ci:test:tango again? I'm sure SegmentationCreateSegment#AddSegmentByUserSiteOrganizationRole would pass this time but it will cost another 3 hours.

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hi @liulukiwi , Im going to forward this pull, as you are confidence with the test. If this test fails, I will create a fix ticket to fix it :) Thanks a lot for your work!

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete,
You're welcome.BTW, it is [passed](https://testray.liferay.com/home/-/testray/case_results/1533383759) this time.

**Pull request closed without merging**
