### PR TITLE
LPS-130270, LPS-130345 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130270
https://issues.liferay.com/browse/LPS-130345

Hi @CarlosBrichete , could you review these cases when you have time? 

Thanks!

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
I'm working on the failure cases and hope I can resend pull with fixed today.

**Comment by CarlosBrichete** [comment]
Thank you very much @liulukiwi !! :D

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
