### PR TITLE
master-lps-130309

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302
https://issues.liferay.com/browse/LPS-130309

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by Jeremy-Ch** [comment]
Hi @CarlosBrichete, I've rebased the above tests and resent a new pr with some newly added tests, please see the details #27

cc/ @austinchiang

**Comment by Jeremy-Ch** [comment]
ci:close

**Pull request closed without merging**
