### PR TITLE
LPS-130302, LPS-130306, LPS-130294, LPS-130293, LPS-130334, LPS-130327 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:tango

**Comment by austinchiang** [comment]
Hey @CarlosBrichete my team spent a day trying to research and write Tango tests and here was what we could produce. We initially wanted to use JSON macros to add a segment with custom criterias/experiences with segments but found out that while the API's exist there seems to be a lot parameters that needed to be passed in to get it to work and we didn't have time to do deeper research on that. So at the end we didn't create any new JSON macros and just extended what we have going in the UI. Hope it's okay.

Also for https://github.com/CarlosBrichete/liferay-portal/pull/23/commits/f4bf195c99bbde9a6ee2299b803e4ff1c0c3b634, this was changed because the sidebar had `Organization` and `Parent Organization` so if we when we selected `Organization` the drag and drop function kept selecting the wrong element from the DOM. I ran the new tests created locally and they passed. Hopefully they don't break existing tests so I'm running `ci:test:tango` here.

**Comment by austinchiang** [comment]
I didn't get the SF errors locally. I think it should be resolved once you update your origin to head

**Comment by austinchiang** [comment]
Pushed a few more tests in the pull

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Hey @austinchiang , thank you very much for your help! I'm already working on a JSON macro to add segments, so don't worry. Let's make these tests pass, then I will refactor them to use the JSON macro.

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
continue in https://github.com/liferay-tango/liferay-portal/pull/1104

**Pull request closed without merging**
