### PR TITLE
LPS-130337,LPS-130338,LPS-130333,LPS-130341,LPS-130326,LPS-130329,LPS-13030,LPS-130331,LPS-130332 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130337
https://issues.liferay.com/browse/LPS-130338
https://issues.liferay.com/browse/LPS-130333
https://issues.liferay.com/browse/LPS-130341
https://issues.liferay.com/browse/LPS-130326

https://issues.liferay.com/browse/LPS-130329
https://issues.liferay.com/browse/LPS-130330
https://issues.liferay.com/browse/LPS-130331
https://issues.liferay.com/browse/LPS-130332

Hi @CarlosBrichete, could you review these cases when you have time?Thanks! For the last 4 cases, I'm not sure they are well written.

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @liulukiwi ! Are you going to fix this one ExperienceCreateExperience#AddNewExperienceSessionReferrerURLSegment ? Or should I? If you are going to do it in another PR or if I have to do it, we can forward this one :)

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete , I will fix this in another pull request.

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete ,  I force push a commit to fix ExperienceCreateExperience#AddNewExperienceSessionReferrerURLSegment in this pr.

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
