### PR TITLE
LPS-130328,LPS-130340, LPS-130333, LPS-130335, LPS-130336

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130328
https://issues.liferay.com/browse/LPS-130340
https://issues.liferay.com/browse/LPS-130333
https://issues.liferay.com/browse/LPS-130335
https://issues.liferay.com/browse/LPS-130336

Hi @CarlosBrichete, could you review these cases when you have time? I also leave a comment in https://issues.liferay.com/browse/LPS-130337, could you please check about that?

Thanks!

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @liulukiwi , it seems this test is failing ExperienceCreateExperience#AddNewExperienceSessionHostnameSegment. Can you check? Thanks a lot :)

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete , I will run LocalFile.ExperienceCreateExperience#AddNewExperienceSessionHostnameSegment
separately in https://github.com/liulukiwi/liferay-portal/pull/354, apart from that, could you please check the commment in https://issues.liferay.com/browse/LPS-130337? thanks!

**Comment by CarlosBrichete** [comment]
Hi @liulukiwi !! Yes, I'll take a look at your comment in the story sorry. About this PR, if you are going to run the failing test in another PR, can we forward this one?

**Comment by liulukiwi** [comment]
Thanks, @CarlosBrichete ,  I will send another pull for the fix, it's up to you send this or not.

**Comment by CarlosBrichete** [comment]
Ok, then I will forward this one :D

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
