### PR TITLE
master-lps-130295_1

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302
https://issues.liferay.com/browse/LPS-130309

https://issues.liferay.com/browse/LPS-130295
https://issues.liferay.com/browse/LPS-130296
https://issues.liferay.com/browse/LPS-130297
https://issues.liferay.com/browse/LPS-130298
https://issues.liferay.com/browse/LPS-130299
https://issues.liferay.com/browse/LPS-130300
https://issues.liferay.com/browse/LPS-130301

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:tango

**Comment by liuxingye** [comment]
Hi @CarlosBrichete, I've rebased and resent this to https://github.com/liferay-tango/liferay-portal/pull/1118 with the fixes for the following cases:
```
LocalFile.SegmentationCreateSegment#AddSegmentBySessionLastSignInDate 
LocalFile.SegmentationCreateSegment#AddSegmentBySessionLocalDate
LocalFile.ExperienceCreateExperience#AddNewExperienceOrganizationOrganizationSegment 
```
/cc @austinchiang

**Comment by liuxingye** [comment]
ci:close

**Pull request closed without merging**
