### PR TITLE
[WIP] LPS-118966 Smoke Poshi Automation: Edit experience name and audience and delete experience

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Hey @CarlosBrichete @ManoelCyreno, we should edit the audience when editing the experience. But this is a first approach of the test. I don't know if it's working as expected 🤔  Let's double-check and complete it. Thanks!

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
See https://github.com/manoelcyreno/liferay-portal/pull/137

**Pull request closed without merging**
