### PR TITLE
LPS-130269 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130269

Hi @CarlosBrichete , cuold you review these cases if you have time?

Thanks!

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
I will take a look at the failure cases.

**Comment by CarlosBrichete** [comment]
Hi @liulukiwi ! I think the failure cases will be fixed in this PR: https://github.com/liferay-tango/liferay-portal/pull/1118 (cc. https://github.com/CarlosBrichete/liferay-portal/pull/27)

**Comment by liulukiwi** [comment]
Thank you @CarlosBrichete , that's great! I will rebase it.

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete
I rebase and resend it here:
#1125

**Pull request closed without merging**
